### ISSUE TITLE
Compact Dark theme does not work on Web eveloper tools

### ISSUE THREAD

**Issue by shiftyshady** [BrowserWorks/waterfox#825] opened 2018-12-23 18:23 UTC
**Describe the bug**

**To Reproduce**
1. Go to We

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by laniakea64** [comment] 2018-12-23 20:49
Duplicate of https://github.com/MrAlex94/Waterfox/issues/826

**Closed as completed** 2021-05-27 11:43 UTC
