### ISSUE TITLE
Issue with Water fox incorrectly loading QRZ.com

### ISSUE THREAD

**Issue by snintendog** [BrowserWorks/waterfox#612] opened 2018-06-11 22:03 UTC
It affects the biography tab in 56.0.1-56.2.0
They use some kind of javascript to put the biographies on the page and Javascript is working in all the other tabs.

No clue what is causing it 54.0.1 works fine along with any other browser i tried Brave, Chrome, Iridium.

![qrz com issue](https://user-images.githubusercontent.com/5448989/41259411-8201a60a-6da1-11e8-9020-4d40173e7364.png)

**Comment by grahamperrin** [comment] 2018-06-12 14:54
Thanks, 

> … No clue …

I can guess a cause, for the https://www.qrz.com/db/KP4PKG example, but we'll know sooner if you can let us have troubleshooting information. 

Text please (**not** the _raw data_ button) copied from: 

- about:support

----

In the meantime: the biography tab appears fine here with 56.2.0.31_5 on FreeBSD-CURRENT.

**Comment by snintendog** [comment] 2018-06-12 22:23
Alright i have one from my personal browser the Asus G75 text doc and one from my uncle that brought this issue up to me.
[Uncs computer waterfox.txt](https://github.com/MrAlex94/Waterfox/files/2095993/Uncs.computer.waterfox.txt)
[Waterfox Asus G75VW.txt](https://github.com/MrAlex94/Waterfox/files/2095994/Waterfox.Asus.G75VW.txt)
 Thank you very much in advance.

**Comment by grahamperrin** [comment] 2018-06-13 22:49
Thanks. 

Both computers have uBlock Origin enabled with multi-process windows disabled. There are known issues with extensions such as uBlock Origin in this situation. 

Whilst I can not reproduce the blockage that's in your screenshot, I _did_ find some unexpected behaviour. 

Please tell whether the blockage is reproducible with uBlock Origin disabled – **completely** disabled, e.g.: 

1. about:addons 
2. disable the extension 
3. reload https://www.qrz.com/db/KP4PKG 

(When uBlock Origin misbehaves, it's not enough to 'switch it off' for a site.)

**Comment by snintendog** [comment] 2018-06-13 23:14
With Ublock Disabled and then a fresh boot of Waterfox it still wouldn't load also what is the multi-process windows i don't remember disabling that.  All the computers had older version of waterfox for the profiles used and specifically my personal computer had the profile folder since firefox 14 would this cause issues as well?

However i did what you did on another of my computers (also affected by the issue) and that fixed it on that computer specifically i will give the trouble shooting info of that computer as well.
[Desk 3000 Computer Waterfox.txt](https://github.com/MrAlex94/Waterfox/files/2100263/Desk.3000.Computer.Waterfox.txt)

Edit: Looked into the Multi Process and enabled it in About config and while it didn't fix my issue it did help my personal computer's performance i will say thank you for that alone.

**Comment by grahamperrin** [comment] 2018-06-14 03:58
> … multi-process windows i don't remember disabling that. …

> … Edit: Looked into the Multi Process and enabled it in About config  …

All three cases 'Disabled by accessibility tools'. If it recurs, this might help:

- [Waterfox disabled multiprocess due to accessibility : waterfox](https://www.reddit.com/r/waterfox/comments/7tupr8/waterfox_disabled_multiprocess_due_to/)

**Comment by grahamperrin** [comment] 2018-06-14 04:04
@snintendog please: is the biography tab affected at _all_ member pages? Today's featured member, for example: 

- https://www.qrz.com/db/HS0DJU#tabs

At _any_ of the three computers, is the biography tab issue reproducible with Waterfox in **safe mode**? The button at about:support

**Comment by snintendog** [comment] 2018-06-14 11:37
It affects all bio tab pages on QRZ on all 3 computers.

All right i ran safe mode and on my personal computer and it displays fine so i started to disable all of my addons then enable them until it works. 

Ublock is obviously one of the issue addons so i disabled that and skipped the enable...Alternate Player for Twitch.tv, CTR, Back/Forward History Tweaks, Classic Toolbar Buttons, Enhancer for YouTube, Firebug, gtranslate, HTTPS Everywhere, New XKit, NoScript, Session Manager, Stylish, Tab Mix Plus wasn't the cause... Tampermonkey was the other Problem addon.
All right so I will have to test on my uncles computer if ublock was the only issue again Restartless restart might be another problem addon if that is the case. 
Thank you for all the help gonna have to get uncle a replacement Adblocker as well as see if that one other addon is the issue.
The desk3000 uses an older version of greasemonkey for my scripts instead of tampermonkey so it seems greasemonkey doesn't cause the issue either.

Once again thank you for helping me through this issue.

I will report back and see if it is fixed on my uncle's computer.
Edit: Disabling both Ublock and Restartless did work on his computer and had to downgrade Ublock to version 1.12.4 to keep using adblocking and qrz.com at the same time.

**Comment by grahamperrin** [comment] 2018-06-14 17:48
OK. 

<strike>I guess, the situation with uBlock Origin will be better if we can identify and port a fix for this: </strike>

- [Findx Privacy Control, Ghostery, Nano Adblocker, Privacy Badger and uBlock Origin are bugged by single-process Waterfox · Issue #580 …](https://github.com/MrAlex94/Waterfox/issues/580)

<strike>– I'm working towards identification at the moment. </strike>

Postscript: the fix should be in the next release of Waterfox for Linux, Mac OS X and Windows.

**Comment by hawkeye116477** [comment] 2019-09-23 22:39
So when uBO (webextension) or Violentmonkey is turned on, then problem is with javascript on Waterfox.
`document.querySelector(".action-render-").contentDocument.querySelectorAll('head style')[0];`
It doesn't return that element, says undefined, but should be `<style type="text/css">`.
Looks like that's fixed from FF 57.

**Comment by hawkeye116477** [comment] 2020-09-16 11:21
@snintendog Is that fixed now? If yes, then should be closed.

**Closed as completed** 2021-05-27 11:39 UTC
