### ISSUE TITLE
Bug with Qwant and French locale

### ISSUE THREAD

**Issue by philipgg** [BrowserWorks/waterfox#879] opened 2019-03-06 21:25 UTC
Hi,

As soon as I select the French locale, the Qwant search engine disappears from the list of search engines, that is nonsense!

Thanks.

**To Reproduce**
Select the French locale.
Check the list of search engines.
Qwant is missing (??)

**Desktop (please complete the following information):**
 - OS: Linux (Debian)
 - Version: Stretch / Buster

**Comment by grahamperrin** [comment] 2019-03-06 23:58
This might have been a norm (not necessarily desirable) in Firefox 56.0.2, upon which Waterfox 56.0 was based. 

https://addons.mozilla.org/addon/qwantcom-for-firefox/versions/ <strike>aim first for </strike>compatible version 3.0.25 seems to not work. 

Instead: 

1. install [Qwant Basic](https://addons.mozilla.org/addon/qwant-com/)
2. please note, [Waterfox: gaining updates to add-ons that require Firefox Quantum : waterfox](https://www.reddit.com/r/waterfox/comments/at0l9j/waterfox_gaining_updates_to_addons_that_require/)

**Comment by philipgg** [comment] 2019-03-07 05:21
Yes, I know I can install Qwant Basic, but I find this issue **_really_** annoying :(

Have a good day.

**Comment by grahamperrin** [comment] 2019-03-07 14:55
If you install the extension, then does Waterfox lose the ability to use Qwant?

**Comment by philipgg** [comment] 2019-03-07 18:41
The extension works well, it's okay...
I think we can close this issue then?

**Comment by grahamperrin** [comment] 2019-03-09 00:50
If you like, you can close it. Or leave it open as a feature (not a bug) with reference to this: 

- Mozilla bug (feature) [1440308 - Add Qwant to the French version of Desktop Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1440308)

> VERIFIED FIXED in Firefox 59

> … contract … search codes to include Qwant in the French version only …

**Closed as completed** 2019-03-14 19:42 UTC
