### ISSUE TITLE
Load pictures in order

### ISSUE THREAD

**Issue by maxoku** [BrowserWorks/waterfox#1153] opened 2019-09-16 15:03 UTC
It's a total chaos when it goes to load pictures. Or it all of them are loading at the same time or they are loading from bottom to top. I can't e.g. start reading a comic right away, I need to wait when all pages will be loaded. If they would just load one by one from top to bottom I could start reading immediately. Is there a way to do that or add such functionality?

**Comment by grahamperrin** [comment] 2019-09-17 02:50
Address please. 

Which version of Waterfox, exactly?

**Comment by maxoku** [comment] 2019-09-17 14:20
@grahamperrin 
Everywhere and each version, it was always that way.

**Comment by grahamperrin** [comment] 2019-09-18 04:41
I do not see the problem. 

> Everywhere

Where?

> a comic 

Where, what's its name?

Again, **please** let us have an address. At least one.

**Comment by maxoku** [comment] 2019-09-18 14:38
Here you go, an example [url](https://manganelo.com/chapter/read_boku_no_hero_academia_manga/chapter_218).
I don't save addresses, so I'll send you more when I encounter a page with many images again.

**Comment by grahamperrin** [comment] 2019-09-19 05:37
Thanks. 

Which version of Waterfox, exactly?

What's your operating system?

Is the issue reproducible with Waterfox in safe mode? 

- about:support

Reproducible with a new profile? 

- about:profiles

Your example, https://manganelo.com/chapter/read_boku_no_hero_academia_manga/chapter_218 

>> Image shows slow or error, you should choose another IMAGE SERVER.

Did you try the other server, number 2?

I tested server number 1 with Waterfox Classic 56.2.14 on FreeBSD-CURRENT with two different profiles, I could not see a problem (the images appear orderly), here's a screen shot with the second profile in safe mode: 

![2019-09-19 06:06 33](https://user-images.githubusercontent.com/192271/65215989-5f9c8e80-daa7-11e9-82e2-ac32f388771f.png)

**Comment by maxoku** [comment] 2019-10-30 18:48
@grahamperrin 
I use Waterfox Classic and keep it up to date, now is 2019.10, Windows 8.1.

On your screen all images are already loaded, so it's not necessary to post it and take so much space.
For me every image was loading at the same time simultaneously. At the beginning not even every image, but randomly chosen:
![boku1](https://user-images.githubusercontent.com/17256400/67888405-52b29680-fb4d-11e9-8c5c-1deca8099e71.jpg)
Small texts are images that haven't started loading yet. Later all images started to load simultaneously.

I was reading a comic on tapas.io and got this:
![tapas](https://user-images.githubusercontent.com/17256400/67886976-b8e9ea00-fb4a-11e9-9faa-45c0510926ae.jpg)
The small text is an image not loaded yet, but you can see that the next image is already loaded before the first one. The first image has loaded later.

**Comment by grahamperrin** [comment] 2019-10-31 18:44
> If they would just load one by one from top to bottom

For <https://manganelo.com/chapter/read_boku_no_hero_academia_manga/chapter_218>, which browsers load images in that way? I do not see it in Firefox or Chromium. 

> a comic on tapas.io 

Can you give the address? Thank you

**Comment by MrAlex94** [comment] 2019-10-31 18:50
As far as I know, all browsers by default will just load images as and when they’re [given them](https://webmasters.stackexchange.com/questions/101174/loading-order-of-assets-stack-how-is-it-managed-by-browser). In no particular order. It’s up to the web developer to load the images in a certain order. I’ll close this because it’s not really a Waterfox specific issue. But you can carry on discussing if you like.

**Closed as completed by MrAlex94** 2019-10-31 18:50 UTC
