### ISSUE TITLE
Can't select text in Waterfox 60.1.0esr Android

### ISSUE THREAD

**Issue by monkeydragon** [BrowserWorks/waterfox#746] opened 2018-09-23 21:33 UTC
When I long tap on any text in a page the text background turns to blue. I can't move the select cursor, and there's no dialog with 'cut', 'copy' etc.

Mi Mix 2, MIUI 10

**Comment by grahamperrin** [comment] 2018-09-23 23:33
Maybe a duplicate of https://github.com/MrAlex94/Waterfox/issues/727

**Comment by MrAlex94** [comment] 2019-06-09 20:39
https://play.google.com/store/apps/details?id=net.waterfox.waterfox

This should be resolved now, please re-open if now :-)

**Closed as completed by MrAlex94** 2019-06-09 20:39 UTC
