### ISSUE TITLE
Missing png file breaks build

### ISSUE THREAD

**Issue by ilikenwf** [BrowserWorks/waterfox#292] opened 2017-11-28 15:08 UTC
On Archlinux AUR (maintainer of waterfox-git), I just removed it from the list for the jar as a workaround, but FYI:

skin/classic/browser/slowStartup-16.png

Doesn't seem to exist for any of the OSes Waterfox supports.

https://aur.archlinux.org/cgit/aur.git/tree/missing-png-workaround.patch?h=waterfox-git

**Comment by jbeich** [comment] 2017-11-29 12:51
Duplicate of #281?

**Comment by ilikenwf** [comment] 2017-11-29 15:29
Yes, apologies. I didn't notice until after submission.

**Comment by grahamperrin** [comment] 2018-05-15 19:08
Review time. Close this?

**Closed as completed** 2018-06-18 12:29 UTC
