### ISSUE TITLE
DRM Not working

### ISSUE THREAD

**Issue by Jaap12345** [BrowserWorks/waterfox#848] opened 2019-01-29 11:02 UTC
The dutch online public television site is not working on Waterfox, but is working on Firefox.

https://www.npostart.nl/draadstaal/28-01-2019/AT_2114372

I think the problem is in the outdated Widevine.
Waterfox: Widevine Content Decryption Module provided by Google Inc. 1.4.8.1008
Firefox: Widevine Content Decryption Module provided by Google Inc. 1.4.8.1146.0

Could you update to the latest Widevine version in the next release?

Or is there a way to update it manually?

Thanks for the good work!

![image](https://user-images.githubusercontent.com/47142342/51903138-dc191a80-23bb-11e9-8319-170c5bacea29.png)

**Comment by Jeferson-Emanuel** [comment] 2019-01-29 17:52
Maybe it is the cause of Netflix not working? I only get a message: Whoops something went wrong... Unexpected error

Simple can't use netflix in waterfox for months now.

**Comment by MrAlex94** [comment] 2019-01-30 01:06
Has been updated in 56.2.7.

**Comment by grahamperrin** [comment] 2019-01-30 03:40
> … can't use netflix in waterfox for months now. …

@Jeferson-Emanuel given the length of time, yours might be a separate issue; not what Waterfox 56.2.7 is fixing.  

If <https://www.reddit.com/comments/700kl1/-/dqvq3sc/> does not resolve the issue for you (it resolved a _Whoops_ case for a user of Waterfox 55), then maybe start a new post at https://www.reddit.com/r/waterfox/

There's also [DRM widevine don't work · Issue #709 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/709) but that, too, might be separate from your issue.

**Comment by Jaap12345** [comment] 2019-01-31 08:02
> 
> Has been updated in 56.2.7.


Thanks! It is working again in 56.2.7. Enjoy the coffee :)

**Comment by grahamperrin** [comment] 2019-01-31 18:46
Thanks for follow-up! 

If you like, close the issue.

**Closed as completed** 2019-01-31 19:39 UTC
