### ISSUE TITLE
Disable MozLZ4

### ISSUE THREAD

**Issue by hook321** [BrowserWorks/waterfox#951] opened 2019-05-08 20:26 UTC
It provides little to no benefits, has negative effects, and makes it unnecessarily difficult for users to modify these files.

**Comment by Squall-Leonhart** [comment] 2019-05-09 18:05
disabling it will also break existing profiles.

so, not happening.

**Comment by hook321** [comment] 2019-05-10 23:31
Not necessarily. When Firefox enabled it it didn't break existing profiles, most likely because they probably made a way to migrate older profiles.

**Comment by Squall-Leonhart** [comment] 2019-05-10 23:41
thats because you can go forwards, but not backwards.

**Comment by hook321** [comment] 2019-05-11 00:45
It's more like compressing and decompressing. Decompressing it should be possible.

**Comment by p1usminus** [comment] 2019-05-12 16:26
> 
> 
> Decompressing it should be possible.

It is possible, with this: https://github.com/avih/dejsonlz4

**Comment by hook321** [comment] 2019-05-12 16:30
Then we should be able to migrate data from profiles that use MozLZ4 over to a profile that doesn't

**Comment by grahamperrin** [comment] 2019-05-12 16:41
Duplicate of #330 (closed).

**Comment by hook321** [comment] 2019-05-12 17:17
Thanks, I don't think I saw that issue. However there was no reason stated for closing it.

**Comment by Squall-Leonhart** [comment] 2019-05-12 20:41
if theres a tool for it, use it.  leave the rest of us alone.

**Comment by MrAlex94** [comment] 2019-05-12 21:45
I understand your concerns, but as outlined [here](https://github.com/MrAlex94/Waterfox/issues/330#issuecomment-491631647) by myself just now I don’t think I’ll disable this. I fear it may also cause engineering issues further down the line. 

You can see in the comments [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1209390) why this happened, so it made sense for Mozilla to do so at the time.

I’ll close this for now, but maybe set an alert on the bug or ping it just to ask if anyone has the time to completely make it LZ4 compliant?

**Closed as completed by MrAlex94** 2019-05-12 21:45 UTC
