### ISSUE TITLE
Corrupted content error

### ISSUE THREAD

**Issue by red-turtle** [BrowserWorks/waterfox#694] opened 2018-07-10 14:24 UTC
Only happens at https://outlook.live.com/mail/inbox and only in Waterfox (haven't seen in Firefox, Chrome or Edge at all).

Happens almost every day, occasionally several times per day. Happens after sitting idle for 30min-8 hours w/ no known trigger for the error. Sometimes takes sitting overnight to trigger.

Clicking "Try Again" button or refreshing page clears it and loads inbox just fine.

**Expected behavior**
Page to load and refresh properly and consistently.

**Screenshots**
![image](https://user-images.githubusercontent.com/41023046/42516057-7281f498-841a-11e8-85d4-e825d9e4332a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**

**Comment by grahamperrin** [comment] 2018-07-10 18:11
Probably a duplicate of this: 

- [(Mozilla 1437080) service workers: load after unload, or session restoration, may lead to 'Corrupted Content Error' or 'Cannot load app' · Issue #581 …](https://github.com/MrAlex94/Waterfox/issues/581)

**Comment by MrAlex94** [comment] 2018-07-12 16:04
(should) hopefully be fixed by:

https://github.com/MrAlex94/Waterfox/commit/7e991d57e06e9b0d52229c7062def23a8ce50158
https://github.com/MrAlex94/Waterfox/commit/d82c62b756b3ff9b250357e0357428a8e8c35f0f
https://github.com/MrAlex94/Waterfox/commit/f874dbfaac9344f25e2f363dd3064fbac25d1bbf

**Closed as completed by MrAlex94** 2018-07-12 16:04 UTC
