### ISSUE TITLE
full-screen-api.warning.delay

### ISSUE THREAD

**Issue by KOTOEB** [BrowserWorks/waterfox#924] opened 2019-04-25 05:27 UTC
**Describe the bug**
full-screen-api.warning.delay value resets to 0 after restart.

**To Reproduce**
1. Go to 'about:config'
2. Search for  'full-screen-api.warning.delay'
3. Set it's value to '999999999'
4. Restart Waterfox

**Desktop (please complete the following information):**
 - OS: [Windows 7 SP1 x64]
 - Version [56.2.9 (x64)]

**Comment by Lorienna** [comment] 2019-04-25 10:52
Was the pref set to `0` in the `user.js` file? That would override `prefs.js` on every startup.

**Comment by KOTOEB** [comment] 2019-04-25 11:52
I don't have user.js in any Waterfox folder.

**Comment by Lorienna** [comment] 2019-04-25 14:39
Well I've tested and couldn't reproduce the issue on Win7.

Does it occur on a fresh add-on-less profile?

**Comment by KOTOEB** [comment] 2019-04-25 16:37
I'm sorry, it's because of the classic theme restorer.

**Comment by grahamperrin** [comment] 2019-04-25 17:54
Thanks, you can close this issue.

**Closed as completed** 2019-04-25 17:55 UTC

**Comment by Lorienna** [comment] 2019-04-26 12:47
@KOTOEB  AFAIK, the latest versions of CTR set the value to `-1`, so you might consider updating the extension.

**Comment by KOTOEB** [comment] 2019-04-26 16:17
@Lorienna Should I delete CTR and reinstall it? Now I have 1.7.7.2 and when I tried to update it from Classic Add-ons archive nothing changes.

**Comment by Lorienna** [comment] 2019-04-26 18:40
Export CTR's preferences > remove the extension > download and install the new version from here:
https://github.com/Aris-t2/ClassicThemeRestorer/releases

<img src="https://user-images.githubusercontent.com/26753987/56829222-d6708b00-686b-11e9-88ee-645f06ec43eb.png" alt="screenshot">

**Comment by KOTOEB** [comment] 2019-04-26 18:56
@Lorienna Thank you very much! Now all is perfect.

**Comment by Lorienna** [comment] 2019-04-26 19:43
Glad I could help!
