### ISSUE TITLE
Close, minimize and maximize buttons are not visible on macOS High Sierra 10.13

### ISSUE THREAD

**Issue by janflyborg** [BrowserWorks/waterfox#220] opened 2017-09-25 18:39 UTC
Just upgraded to macOS 10.13 and ran Waterfox. Everything seems to be working well, except that the red, yellow and green buttons at the leftmost top of the window (the ones you use for close, minimize and maximize the window) are not visible.

Please see this image:

![no_buttons](https://user-images.githubusercontent.com/12851853/30824913-6d7a4b74-a231-11e7-999c-4a1ee5686d5e.jpg)

**Comment by janflyborg** [comment] 2017-09-25 18:41
Just an update. Tried to click them and they seem to be there. Only not visible.

**Comment by MrAlex94** [comment] 2017-09-25 23:28
Going to update to macOS 10.13 and check it out myself :-)

**Comment by MrAlex94** [comment] 2017-09-26 16:54
Just an update, a temporary workaround while I get this remedied is to go to Menu>Customize>Title Bar.

<img width="1440" alt="screen shot 2017-09-26 at 17 54 16" src="https://user-images.githubusercontent.com/4728920/30873013-c5334336-a2e3-11e7-8e93-01645c1e0f08.png">

**Comment by Scientist333** [comment] 2017-09-26 17:37
Thank You

**Comment by janflyborg** [comment] 2017-09-26 19:32
Thanks for that. I have now downgraded to 10.12 (since NVIDIA does not support the graphic card in my Mac Pro for 10.13 yet), so this problem is not so urgent for me anymore.

**Comment by Tacolizard** [comment] 2017-11-24 03:04
same problem here. thanks for the workaround. it kinda ruins the aesthetic though

**Comment by MrAlex94** [comment] 2017-11-24 18:06
It has been fixed in 56 which you can test [here](https://t.co/NeHmZ0r5fc).

**Comment by auxbuss** [comment] 2017-12-28 10:24
New user here. I just installed 56.0.1 on macOS 10.13.2 and this problem occurred. fyi: I imported my Firefox settings on first loading Waterfox.

**Comment by grahamperrin** [comment] 2017-12-30 10:19
Cross reference [Red-Yellow-Green (Close-Minimize-Expand) dots gone after MacOS High Sierra install : waterfox](https://www.reddit.com/r/waterfox/comments/7kqvux/redyellowgreen_closeminimizeexpand_dots_gone/)

Not reproducible with Waterfox 56.0.1 on build 17C76a of Mac OS X 10.13.2: 

![2017-12-30 10 24 15](https://user-images.githubusercontent.com/192271/34453494-a2cfea8c-ed4e-11e7-84e3-08b425fe1ead.png)

----

Two questions for @auxbuss 

At `about:config` if you set `browser.tabs.drawInTitlebar` to `false`, does the problem persist? 

Is the problem reproducible with Waterfox in safe mode? 

Menu ▸ ? ▸ Restart with Add-ons Disabled…

**Comment by auxbuss** [comment] 2017-12-30 14:01
@grahamperrin `browser.tabs.drawInTitlebar` appears to be set via the `Title Bar` checkbox (as mentioned by @MrAlex94 above), so yes that is the fix I've used.

The problem is absent in safe mode. However, it persists in normal mode even after disabling all add-ons manually and restarting.

**Comment by grahamperrin** [comment] 2017-12-30 21:15
Thanks, can you share a screenshot? Do you have anything in a [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css) file? 

A long shot, try changing the appearance first to (say) _Compact Light_ then to _Default 56.0.1_ …

**Comment by auxbuss** [comment] 2017-12-31 09:01
![screen shot 2017-12-31 at 08 41 15](https://user-images.githubusercontent.com/82220/34460511-a0032df4-ee08-11e7-92af-6208d5b56801.png)

` userChrome.css`:
```
/* Tab bar below Navigation & Bookmarks Toolbars

  For best results, show Title Bar or Menu Bar */
  #nav-bar { /* main toolbar */
  -moz-box-ordinal-group: 1 !important;
  border-top-width: 0 !important;
   }
    #PersonalToolbar { /* bookmarks toolbar */
   -moz-box-ordinal-group: 2 !important;
   }
   #TabsToolbar { /* tab bar */
 -moz-box-ordinal-group: 3 !important;
   }
```
The problem persists after switching themes.

**Comment by grahamperrin** [comment] 2017-12-31 13:18
OK, thanks, that's a different issue (and not an issue with Waterfox): 

- close, minimize and maximize buttons **are** visible
- there's an overlap
- the overlap is proper, given your preference to have the main toolbar uppermost

– the **tab bar**, not the main toolbar, has the space that's intended to prevent overlap when the user prefers tabs in the title bar. If you'd like to remove that space, try the solution at <https://redd.it/742bpv>.

To prevent the overlap in your case (plus a few more goodies, for which I can't take credit): 

```text
/* main toolbar uppermost, with padding to avoid overlap when 
	browser.tabs.drawInTitlebar is true on Mac OS X 10.13.x,  
	and the tab bar below the bookmarks toolbar */

#nav-bar { /* main toolbar */
	-moz-box-ordinal-group: 1 !important;
	border-top-width: 0 !important;
	padding-left: 65px !important;
}

#PersonalToolbar { /* bookmarks toolbar */
	-moz-box-ordinal-group: 2 !important;
}

#TabsToolbar { /* tab bar */
	-moz-box-ordinal-group: 3 !important;
}

/* Waterfox menu as close as possible to the Apple menu */

#PanelUI-button, #customization-panel-container,
#customization-panelWrapper .panel-arrow,
#ctr_panelui-button,
#wrapper-ctr_panelui-button {
	-moz-box-ordinal-group: 0
}

#PanelUI-button {
	background-position: 100% 0, calc(100% - 1px) 0, calc(100% - 2px) 0;
}


#PanelUI-popup {margin-right:-350px!important;}
#PanelUI-popup .panel-arrow {margin-right:340px!important;}
```

The effect on FreeBSD, where I prefer an undisrupted title bar: 

![2017-12-31 13 13 16](https://user-images.githubusercontent.com/192271/34461802-8c107850-ee2c-11e7-9ec6-2ca3c1bc48a3.png)

– on Mac OS X, the effect will probably be close to what you want. 

---- 

If what's above doesn't suit you, then the best place to ask may be https://www.reddit.com/r/FirefoxCSS/ – just make clear that you're working with a 56.x version. 

Side note: if you have not already tried it, try [Stylish](https://addons.mozilla.org/addon/stylish/) (the latest release is 3.0.1 but I prefer 2.1.1).

**Comment by grahamperrin** [comment] 2018-05-15 19:15
Review time. 

Maybe close this? (Is there a bug _in Waterfox_?)

**Closed as completed** 2018-06-18 12:15 UTC
