### ISSUE TITLE
Waterfox crashes when navigating to reddit.com

### ISSUE THREAD

**Issue by TalviT** [BrowserWorks/waterfox#260] opened 2017-11-03 17:42 UTC
Hey,

I have just installed Waterfox and so far I am very happy with it, but the browser always crashes when I try to navigate to reddit.com. Other sites work fine.

I started Waterox via the terminal and this is the log output:
```
[Parent 25541] WARNING: pipe error (51): Die Verbindung wurde vom Kommunikationspartner zurückgesetzt: file /home/alex/Waterfox/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
[Parent 25541] WARNING: pipe error (45): Die Verbindung wurde vom Kommunikationspartner zurückgesetzt: file /home/alex/Waterfox/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353

###!!! [Parent][MessageChannel] Error: (msgtype=0x800017,name=PHttpChannel::Msg_DeleteSelf) Channel error: cannot send/recv

###!!! [Parent][MessageChannel] Error: (msgtype=0x280080,name=PBrowser::Msg_Destroy) Channel error: cannot send/recv
```
Line 1 and 2 translated: "The connection has been reset by the communication partner".
Line 3 is repeated 24 times in the original, I have shortened it here.

Additional notes: I'm running version 55.2.2 on a Linux machine. The Bug does not occur in Firefox, which I currently have installed next to it.

**Comment by MrAlex94** [comment] 2017-11-22 00:50
Could you try modifying **security.sandbox.content.level**? Set it to 1 or 0.

**Comment by benoit-pierre** [comment] 2017-11-22 09:08
@MrAlex94: I just tried, changed it from 2 to 1 or 0, and it still crashes.

**Comment by criztovyl** [comment] 2017-11-22 09:51
Dunno if it's the same, but what happens when launching with `MOZ_DISABLE_CONTENT_SANDBOX=1` environment variable?

**Comment by benoit-pierre** [comment] 2017-11-22 09:56
@criztovyl: crash.

**Comment by criztovyl** [comment] 2017-11-22 14:38
Which Linux distro are you on?

**Comment by benoit-pierre** [comment] 2017-11-22 14:47
I'm on Arch Linux, and using the pre-built waterfox binary (installed from [AUR](https://aur.archlinux.org/packages/waterfox-bin/)).

**Comment by criztovyl** [comment] 2017-11-22 16:18
Maybe try running from gdb for getting a backtrace? ^^

(Launch with `gdb path/to/waterfox`, type `run` and after crash do `bt` (for backtrace).)

**Comment by benoit-pierre** [comment] 2017-11-22 16:28
```
Thread 1 "waterfox" received signal SIGSEGV, Segmentation fault.
0x00001555477bbaf8 in ?? () from /opt/waterfox/libxul.so
(gdb) bt
#0  0x00001555477bbaf8 in  () at /opt/waterfox/libxul.so
#1  0x00001555477bb1d7 in  () at /opt/waterfox/libxul.so
#2  0x00001555473bccac in  () at /opt/waterfox/libxul.so
#3  0x00001555476f5b28 in  () at /opt/waterfox/libxul.so
#4  0x000015554957e126 in  () at /opt/waterfox/libxul.so
#5  0x000015554957824b in  () at /opt/waterfox/libxul.so
#6  0x000015554956dfd2 in  () at /opt/waterfox/libxul.so
#7  0x000015554957e149 in  () at /opt/waterfox/libxul.so
#8  0x000015554957e396 in  () at /opt/waterfox/libxul.so
#9  0x00001555498be3b2 in  () at /opt/waterfox/libxul.so
#10 0x000015554957e126 in  () at /opt/waterfox/libxul.so
#11 0x000015554957824b in  () at /opt/waterfox/libxul.so
#12 0x000015554956dfd2 in  () at /opt/waterfox/libxul.so
#13 0x000015554957e149 in  () at /opt/waterfox/libxul.so
#14 0x000015554957e396 in  () at /opt/waterfox/libxul.so
#15 0x00001555498be978 in  () at /opt/waterfox/libxul.so
#16 0x000015554957e126 in  () at /opt/waterfox/libxul.so
#17 0x000015554957824b in  () at /opt/waterfox/libxul.so
#18 0x000015554956dfd2 in  () at /opt/waterfox/libxul.so
#19 0x000015554957e149 in  () at /opt/waterfox/libxul.so
#20 0x000015554957e396 in  () at /opt/waterfox/libxul.so
#21 0x00001555498640c6 in  () at /opt/waterfox/libxul.so
#22 0x00001555474db5f5 in  () at /opt/waterfox/libxul.so
#23 0x000015554784c560 in  () at /opt/waterfox/libxul.so
#24 0x000015554784d036 in  () at /opt/waterfox/libxul.so
#25 0x0000155547842973 in  () at /opt/waterfox/libxul.so
#26 0x00001555478437c3 in  () at /opt/waterfox/libxul.so
#27 0x0000155547835866 in  () at /opt/waterfox/libxul.so
#28 0x0000155546da3705 in  () at /opt/waterfox/libxul.so
#29 0x0000155546c445c8 in  () at /opt/waterfox/libxul.so
#30 0x0000155546c44509 in  () at /opt/waterfox/libxul.so
#31 0x0000155546d5ffe5 in  () at /opt/waterfox/libxul.so
#32 0x0000155546d9b1b4 in  () at /opt/waterfox/libxul.so
#33 0x0000155545dbea1b in  () at /opt/waterfox/libxul.so
#34 0x0000155545dc29a7 in  () at /opt/waterfox/libxul.so
#35 0x00001555462e2256 in  () at /opt/waterfox/libxul.so
#36 0x000015554627f6f9 in  () at /opt/waterfox/libxul.so
#37 0x0000155548040436 in  () at /opt/waterfox/libxul.so
#38 0x00001555492fc999 in  () at /opt/waterfox/libxul.so
#39 0x000015554938fa33 in  () at /opt/waterfox/libxul.so
#40 0x0000155549390191 in  () at /opt/waterfox/libxul.so
#41 0x0000155549390747 in  () at /opt/waterfox/libxul.so
#42 0x000000000045bacd in  ()
#43 0x0000155554612f6a in __libc_start_main () at /usr/lib/libc.so.6
#44 0x000000000045b6da in _start ()
```

**Comment by grahamperrin** [comment] 2017-12-24 06:07
If you enable multiprocess, then is crashing limited to a tab (without crashing the browser)?

Is the issue reproducible with Waterfox 56.x?

**Comment by benoit-pierre** [comment] 2017-12-24 11:05
I don't have access to my machine, so this will have to wait until I'm back at home next year.

**Comment by grahamperrin** [comment] 2018-01-04 17:12
@benoit-pierre hi, will you have an opportunity to try with the most recent version of Waterfox?

If the crash is reproducible with 56.x, it will be helpful to see troubleshooting information. From: 

about:support

**Comment by benoit-pierre** [comment] 2018-01-11 16:05
No crash with Waterfox 56.0.2.

**Comment by WagnerGMD** [comment] 2018-01-28 04:06
Sometimes reddit is little strange... It didn't crash but apparently the CSS has a few trouble (big white space instead of main theme section) to be display correctly. It has happened a few times these last weeks (but I won't be able to remind myself more).

**Comment by grahamperrin** [comment] 2018-05-15 19:05
Review time. Close this?

**Comment by WagnerGMD** [comment] 2018-05-17 12:35
```
reddit.com 1st-party * allow
reddit.com redditmedia.com * allow
reddit.com redditmedia.com css allow
reddit.com redditmedia.com image allow
reddit.com redditstatic.com * allow
reddit.com redditstatic.com css allow
reddit.com redditstatic.com image allow
reddit.com redditstatic.com script allow
```
That's the rules for (the addon) **uMatrix-v1.1.4**. One advice : don't forget to enable cookie(s) (allow them only for reddit).
Otherwise reddit didn't show any crash (until now). The main trouble is only about the website interface (CSS, pictures, etc) which refuse to load correctly (and the cause is just another bad design from reddit. Damn it (idiot reddit) no we don't need the cookie to load anything related to the interface).

**Closed as completed** 2018-06-18 12:22 UTC
