### ISSUE TITLE
Portable version of Waterfox

### ISSUE THREAD

**Issue by tcreek** [BrowserWorks/waterfox#943] opened 2019-05-07 16:14 UTC
At the portableapps.com site, they only include Firefox Portable. 

With the ever growing censorship at Mozilla, it would be nice to offer an alternative.

**Comment by grahamperrin** [comment] 2019-05-07 19:17
[Waterfox (64-Bit variant of Firefox) | PortableApps.com](https://portableapps.com/node/30886)

[Has WaterfoxPortable been discontinued? | PortableApps.com](https://portableapps.com/node/60159)

**Comment by tcreek** [comment] 2019-05-07 20:12
Yeah, here is the problems. 

1) PortableApps.com web site is much more visited, and well known
2) Waterfox site is not all that friendly for downloading various versions.
It seems there have been some updates, and now I see the portal version on the site. Before it was not even shown on the site. That is why I brought it up. 
For the mobile versions, the former site would take you to each phone's store, and not even offer up a direct download of the application. Now on the new site, mobile versions are not even shown.

Maybe offering ProtableApps the portable version directly would help? 
What about a Portable Linux version?

**Comment by MrAlex94** [comment] 2019-05-07 20:52
>  What about a Portable Linux version?

Technically the Linux versions is as portable as it could get, in the sense you can just put it on a USB and run it from anywhere since it's just the program files in a tarball.

**Comment by jrappen** [comment] 2019-05-09 09:26
Any plans for a portable Waterfox 68 and later?

**Comment by grahamperrin** [comment] 2019-05-12 10:51
> … put it on a USB and run it from anywhere …

It could benefit from profile-related paths being set to use removable media. 

This is not an expectation that @MrAlex94 should spend time on this for users of Linux; anyone with relevant coding skills might submit a pull request. 

----

Re: unexpected use of non-removable media on Windows, there's this https://www.reddit.com/comments/bmit86/-/en6vjss/?context=3 – I'm not sure what to make of it but at a glance I see no evidence of a bug.

**Comment by grahamperrin** [comment] 2019-07-13 18:54
> portable Waterfox 68 

▶ https://www.reddit.com/r/waterfox/comments/cco5gl/will_there_be_a_waterfox_alpha_portable/etp2kjp/

**Comment by jrappen** [comment] 2020-03-19 21:53
@MrAlex94 Any updates?

**Comment by MrAlex94** [comment] 2020-03-20 11:00
Sorry! There are plans, just need to update the scripts to handle Portable as well.

**Comment by jrappen** [comment] 2020-05-04 20:50
@MrAlex94 I’d appreciate resolving this for the May release.

If you’re busy, any pointers on how to fix this?

—-

@tcreek maybe you could fix your typo in the title?

**Comment by Risae** [comment] 2020-07-26 18:15
You guys got an update on this? Would love to have a native portable edition of Waterfox!
Having portable settings available in Current would also be a worthy reason to finally upgrade from Classic.

**Comment by jrappen** [comment] 2020-09-24 23:03
@MrAlex94 We went from one of two release channels being released as portable to zero.

**Comment by jrappen** [comment] 2021-02-12 13:50
@MrAlex94 It's been almost another year. Any updates?

**Comment by HyperCriSiS** [comment] 2021-02-14 20:40
Can you please change how the portable version is typically launched?

I would like to run several portable instances side by side but this does not work properly.
One of the portable instances should run as the main which is registered in the system and pinned to taskbar. 
I tried every possible solution I found but it never fully works. The issue is, that the Waterfox.exe is not launched directly.

Can you modify the Waterfox.exe to make this working?

**Closed as completed** 2021-05-27 11:46 UTC

**Comment by jrappen** [comment] 2021-05-27 12:33
@MrAlex94 What is the resolution here?

**Comment by mzso** [comment] 2021-05-27 16:10
[**@jrappen**](https://github.com/jrappen) commented on [2021. máj. 27. 14:33 CEST](https://github.com/MrAlex94/Waterfox/issues/943#issuecomment-849593956 "2021-05-27T12:33:13Z - Replied by Github Reply Comments"):
> [@MrAlex94](https://github.com/MrAlex94) What is the resolution here?

It seems like there's a mass closing of WF Classic, issues. Even though this is not such. But it might have been closed by accident.

**Comment by jahnson** [comment] 2022-01-28 17:18
What is the status of this?  Is there a WF current portable version coming?  
The standard installer allows one to choose the installation directory, but then it dumps stuff in Appdata anyway.  
The WF portable on portapps.io seems to be based on classic.

**Comment by ioc2e3** [comment] 2025-07-20 11:29
> Technically the Linux versions is as portable as it could get, in the sense you can just put it on a USB and run it from anywhere since it's just the program files in a tarball.

That ...

I only know how to ( surf the Internet ) and ( decompress use WinRAR ) ...

.
