### ISSUE TITLE
add-on could not be installed because it appears to be corrupt

### ISSUE THREAD

**Issue by unicorndreams** [BrowserWorks/waterfox#955] opened 2019-05-10 12:32 UTC
**Describe the bug**
When trying to install some add-ons, either directly from Mozilla, or from a local downloaded file, Waterfox throws these errors:

"The add-on downloaded from this site could not be installed because it appears to be corrupt."
"This add-on could not be installed because it appears to be corrupt."

The error occurs if the add-on's "manifest.json" doesn't have an "applications" entry.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://addons.mozilla.org/en-GB/firefox/addon/cookie-quick-manager/ (or mostly any theme).
2. Click on [Install] (or right-click, download the .XPI file, go to Tools - Add-ons - Install Add-on from file" and install the downloaded file).
3. Error message will pop-up.

**Expected behaviour**
Waterfox should install the add-ons.

**Screenshots**
![image](https://user-images.githubusercontent.com/11075627/57527329-c0e87000-7305-11e9-887a-c17c383c787e.png)
![image](https://user-images.githubusercontent.com/11075627/57528794-a1534680-7309-11e9-8c16-610e1b1828f1.png)

**Desktop**
 - OS: Windows 7.
 - Version 7 64 bits.

**Additional context**
The problem can be easily solved by adding this simple line to "manifest.json" in the add-ons' files:

"applications": { "gecko": { "id": "X@Y" } },

After repacking the add-on, it is perfectly loaded by Waterfox (obviously, disabling the signature check, as editing the "manifest.json" file breaks the signature checksum).

The "id"'s X and Y maybe anything strings, as long as there is an at "@" character (the lack of the "@" also causes Waterfox to throw the error and refuse the add-on).

Unpacking and loading the add-on directly in about:debugging also works, but that's a temporary workaround.

**Comment by laniakea64** [comment] 2019-05-10 12:51
Duplicate of https://github.com/MrAlex94/Waterfox/issues/936#issuecomment-489872863

**Comment by unicorndreams** [comment] 2019-05-10 13:00
Ah, I see. It has to do with the "manifest.json" AND the certification junk...

**Comment by MrAlex94** [comment] 2019-05-12 21:54
Have closed this due to its relation with the other issue. Re-open if needed :-)

**Closed as completed by MrAlex94** 2019-05-12 21:54 UTC

**Comment by unicorndreams** [comment] 2019-05-13 05:24
Adding the PEM, posted on the other thread (https://www.velvetbug.com/benb/icfix/), into Waterfox certificates solved the problem (at least, for the add-ons I use, as I understood it, there are still some that are still being refused for whatever reason...) 

Anyway, thanks for pointing that out!

**Comment by LeeBinder** [comment] 2019-05-13 18:41
Both, the icfix.pem from Ben B's velvetbug server and the extension approach by Mozilla ONLY work for Waterfox 56.2.9 Desktop, NOT for Waterfox 56.1.0 Android!

I have uploaded the certificate to my server with the correct MIME type and compiled a write-up how to import the certificate which works for both. You can find it [here](https://github.com/MrAlex94/Waterfox/issues/936#issuecomment-491090950).

**Comment by RaviOnline** [comment] 2019-10-01 07:06
@unicorndreams Thank you for posting the solution in detail. Having an '@' in the add-on id was critical to solving this issue. I had read the comment 936 before but it was missing this little but important detail. Thanks a lot once again!
