### ISSUE TITLE
Waterfox Classic portable 56.2.12 maybe not using the portable profile – attention to about:profiles

### ISSUE THREAD

**Issue by grahamperrin** [BrowserWorks/waterfox#1154] opened 2019-09-18 05:41 UTC
From #980: 

> … the exe is automatically started with the portable mode's profile. …

With Waterfox Classic portable 56.2.14 – auto-updated from 56.2.12 – I don't see this. 

Screen recording: [2019-09-18 06:07.zip](https://github.com/MrAlex94/Waterfox/files/3624553/2019-09-18.06.07.zip)

Two frames from the recording: 

![2019-09-18 06:17:15 frame](https://user-images.githubusercontent.com/192271/65114014-33b4d680-d9dd-11e9-81e8-717189ac1412.png)

> `LastProfileDirectory=C:\Users\gjp4.UNIVERSITY\Downloads\WaterfoxPortable\Data\profile`

![2019-09-18 06:17:36 frame](https://user-images.githubusercontent.com/192271/65114024-39aab780-d9dd-11e9-8c66-03597a79a601.png)

– no such profile at about:profiles

At a glance, `WaterfoxPortable.exe` seems to behave as if it's `Waterfox.exe` (a non-portable Waterfox Classic that was performed by an administrator). 

More specifically, it seems as if: 

- Waterfox Classic portable 56.2.14 does not (or does not always) use `WaterfoxPortableSettings.ini`

– am I missing something?

**Comment by grahamperrin** [comment] 2019-09-18 05:53
Meta, tracking: #538

Afterthought: 

> auto-updated from 56.2.12 

I wonder, is this issue an unexpected consequence of #1132 and the incorrect packing?

Possibly related: 

- [Waterfox Portable Always Tries To Restore Old Session On Start Up](https://www.reddit.com/r/waterfox/comments/d59lab/waterfox_portable_always_tries_to_restore_old/)

– a question from me at https://www.reddit.com/comments/d59lab/-/f0nyldh/

**Comment by grahamperrin** [comment] 2019-09-18 06:43
Hmm. I: 

1. trashed the previous installation of Waterfox Classic portable
2. performed a (hopefully) fresh installation of (mis-packed) Waterfox Classic portable 56.2.12 to a different path
3. set Waterfox Classic portable 56.2.12 to never check for updates. 

I'm not sure how to interpret the end results. 

Waterfox Classic portable 56.2.12 about:profiles shows the non-portable Waterfox Classic _default_ profile in use, in this case: 

`C:\Users\gjp4.UNIVERSITY\AppData\Roaming\Waterfox\Profiles\9znzp3u8.default`

– **and does not** list the path to the portable profile, in this case: 

`C:\Users\gjp4.UNIVERSITY\Desktop\WaterfoxPortable\Data\profile`

I naturally assumed that a change to preferences with the _default_ profile in use would be effective for subsequent use of non-portable Waterfox Classic with the same profile. 

Unless I'm missing something, that assumption was wrong; another screen recording: 

- [2019-09-18 07:27.zip](https://github.com/MrAlex94/Waterfox/files/3624812/2019-09-18.07.27.zip)
- https://put.re/player/fMTXg9Qc.mp4

**Comment by tcreek** [comment] 2019-09-21 01:09
Isn't this basically a duplicate of 

https://github.com/MrAlex94/Waterfox/issues/912

Which describes the same behavior?

**Comment by grahamperrin** [comment] 2019-09-21 12:03
https://github.com/MrAlex94/Waterfox/issues/912#issue-429379383 is essentially about 

> absolute paths to some installed add-ons 

#912 may be a duplicate of an earlier issue, the one linked from https://github.com/MrAlex94/Waterfox/issues/912#issuecomment-529040197

Here: … **attention to about:profiles**

There may be some overlap with earlier issues but for this issue #1154 it may be useful to exclude add-ons from the mix.

**Comment by grahamperrin** [comment] 2019-10-01 19:04
> … am I missing something?

Maybe the PortableApps.com Platform™? https://portableapps.com/platform/features

Is Waterfox portable intended to be usable without the Platform menu?

**Closed as completed** 2021-05-27 11:56 UTC
