### ISSUE TITLE
GitHub is no longer supports Waterfox

### ISSUE THREAD

**Issue by vanowm** [BrowserWorks/waterfox#786] opened 2018-11-07 15:48 UTC
Just a heads up, GitHub no longer works 100% in Waterfox, specifically we no longer can preview issue messages or edit them.

**Comment by grahamperrin** [comment] 2018-11-07 15:57
#784 

Duplicate of recently closed [Github stopped working in Waterfox due to "outdated version of Firefox" · Issue #785 …](https://github.com/MrAlex94/Waterfox/issues/785)

**Closed as completed** 2018-11-07 15:59 UTC
