### ISSUE TITLE
Amazon Prime Video still reporting browser update required (now v 56.2.14)

### ISSUE THREAD

**Issue by tcreek** [BrowserWorks/waterfox#1117] opened 2019-08-31 06:32 UTC
From the Blog Post on August 19, 2019 it is stated, 

"Fix for websites that require EME such as Netflix, Prime Video etc and few other small changes."

https://www.waterfox.net/blog/waterfox-56.2.13-release-download/

So I visit the Amazon Prime Video site, attempt to watch a video then get this:

![waterfox_prime](https://user-images.githubusercontent.com/4149717/64060204-0ec40500-cb8f-11e9-8c14-34a7b4b09564.JPG)

I have verified this on Windows 10 & Debian 9 with the same result

**Comment by grahamperrin** [comment] 2019-08-31 07:04
Meta, tracking: #538

Cross reference: [Latest version of WF, Amazon Prime still not working](https://www.reddit.com/r/waterfox/comments/ctg797/latest_version_of_wf_amazon_prime_still_not/) and partial duplicate https://redd.it/cxfpg5 

See also: #709

> Debian

See also: #1051

**Comment by tcreek** [comment] 2019-08-31 07:29
In this case, Widevine appears to be functioning as tested at http://demo.theoplayer.com/drm-aes-protection-128-encryption then selecting the DRM playback.

Seems Amazon just don't like the version it is being presented for whatever reason.

**Comment by Commissar0617** [comment] 2019-09-08 22:19
lets put it this way... the version of FF that classic is built on, is nearly 2 years old. websites/addons, especially those with drm, are beginning to cease support of that version or just not function at all on it.

**Comment by tcreek** [comment] 2019-09-09 04:34
What is odd, trying Web 3.22.7, I get a different message

 
>Prime Video titles can't be watched on this device because the operating system isn't supported. >For more information, 

Though it clearly states Linux is supported. This is what Web is reporting to sites.

> Browser: Safari
> Device Type: Desktop
> Operating System: Linux
> Browser Identification String: 
>    Mozilla/5.0 (X11; Linux x86_64)
>    AppleWebKit/605.1 (KHTML, like Gecko)
>    Version/11.0 Safari/605.1 Debian/9.0
>    (3.22.7-1) Epiphany/3.22.7

**Comment by grahamperrin** [comment] 2019-09-26 05:06
Cross reference: 

- https://redd.it/d91j8x

– <strike>some uncertainty re: the version of Waterfox, I think it's </strike>Waterfox Classic.

**Comment by grahamperrin** [comment] 2019-10-17 05:49
This week's Waterfox Classic 2019.10 (20191015002329) on Manjaro: 

![image](https://user-images.githubusercontent.com/192271/66980871-0b86c900-f0aa-11e9-98cc-8a667d185f1a.png)

… I didn't expect a fix; just noting that it does still appear to be bugged.

**Comment by MrAlex94** [comment] 2019-10-17 14:12
DRM hasn't ever worked on Waterfox Classic on *nix style OSs. I remember
spending time a couple of years ago looking into why, but could never
locate the issue.

**Comment by tcreek** [comment] 2019-10-17 14:21
Not complaining about the DRM, as I have shown it works (at least on Windows), but sites are reporting the version of the browser is out of date,

**Comment by grahamperrin** [comment] 2019-10-18 03:44
> reporting the version of the browser is out of date,

On Linux, yes?

**Comment by tcreek** [comment] 2019-10-18 03:50
Trying the link above for DRM on a Linux machine, it is reporting:

![drm_linux](https://user-images.githubusercontent.com/4149717/67064528-7d095a80-f130-11e9-86aa-89f8cf85764f.png)

**Comment by grahamperrin** [comment] 2019-10-18 17:41
The DRM error there is probably unrelated to the problem with Amazon Video. 

On Windows, https://www.amazon.co.uk/gp/video/detail/B00X674KKU/ref=stream_est_sd_mv?autoplay=1&t=145 in Waterfox Classic 2019.10 (20191016181224) there's Amazon playback of DRM content alongside the reported exception at <http://demo.theoplayer.com/drm-aes-protection-128-encryption>: 

![image](https://user-images.githubusercontent.com/192271/67115786-de840480-f1d6-11e9-83a7-7c7d8430c54a.png)

**Comment by grahamperrin** [comment] 2019-10-19 09:23
> ## Amazon Prime Video … not functioning … 56.…

> it works (at least on Windows), 

@MrAlex94 does Amazon Video also work on macOS? If so, we might close this #1117 as a duplicate of: 

- [Waterfox Classic on Linux: Encrypted Media Extensions not working for DRM-protected content such as Amazon video · Issue #1051 …](https://github.com/MrAlex94/Waterfox/issues/1051)

**Comment by tcreek** [comment] 2019-10-19 15:11
As I keep mentioning, it's not about the DRM in this case, but the "browser update required"

**Comment by grahamperrin** [comment] 2019-10-19 17:22
OK, would you like to edit the subject line? To more easily distinguish between the two issues, at a glance. 

Thanks

**Comment by codeman101** [comment] 2020-11-24 20:23
I see a similar error with netflix after compiling the latest on the master branch. (WF current 10.2020

**Closed as completed** 2021-05-27 11:55 UTC
