### ISSUE TITLE
Extension "Scrapbook X" has an issue with WaterFox56

### ISSUE THREAD

**Issue by iiv3** [BrowserWorks/waterfox#309] opened 2017-12-11 00:02 UTC
Start with clean profile (no imports). Install "Scrapbook X" extension. Restart Waterfox.
Open "kernel.org". Save the webpage with "scrapbook". When a notification appears (at top right corner) click it to open the saved page or alternatively open the page through the menu or sidebar (alt+k). You'll see error for missing page/file.

The `index.html` file has not been saved. The directory and some other files (fonts and css) exist, but no html is saved on the disk.

The "older" extension "Scrapbook" seems to work fine.
The older WaterFox55.2.2  and the original "Firefox 56" does work with "Scrapbook X".

I'm running Linux Slackware64 current.
The current "Scrapbook X" version seems to be 1.14.4 from December 4, 2017.

**Comment by jdunn0** [comment] 2017-12-20 14:20
I recently noted on the [ScrapBook X issue tracker](https://github.com/danny0838/firefox-scrapbook/issues/235#issuecomment-352690502) that this issue might be caused by e10s (Multi-Process Support) being enabled when the extension is not compatible with e10s.

The author mentioned that the extension is marked as not compatible with e10s so there might be an issue with Waterfox enabling e10s support even when extensions that are not compatible are installed.

**Comment by iiv3** [comment] 2017-12-22 13:28
The Waterfox release notes does mention: "Enabled e10s by default, some add-ons that aren’t marked as compatible may cause unexpected behaviour."

Turning off `Edit->Preferences->General->Enable multi-process Waterfox` does fix the issue.
It seems to be linked to `about:config` `browser.tabs.remote.autostart`.

The Electrolysis mozilla page mentions that `browser.tabs.remote.force-enable` could be used to force e10s even when addons disable it. So the `autostart` should not force e10s when addon is marked as not compatible...

On Firefox 56, at clean install `autostart` is set to `false`, but there is `autostart.2` that is set to `true`. The e10s is enabled by default, but installing "Scrapbook X" disables it, as it should.

**Comment by jbeich** [comment] 2017-12-22 14:40
> autostart should not force e10s when addon is marked as not compatible

After 9c4cc5585e2d e10s is always enabled by default, even if an addon flipped `extensions.e10sBlockedByAddons` pref. In FF56 `extensions.e10s.rollout.policy` is set to `50allmpc` allowing even non-Mozilla addons which have `multiprocessCompatible` flag set to `true` to keep e10s enabled. WF56 broke the logic by removing **e10srollout** in 2a860d648484.

Just a guess.

https://github.com/MrAlex94/Waterfox/blob/9ec4a8109122e21ba639c999da33c292dbb381b9/toolkit/mozapps/extensions/internal/XPIProvider.jsm#L3965-L3968
https://github.com/MrAlex94/Waterfox/blob/9ec4a8109122e21ba639c999da33c292dbb381b9/toolkit/mozapps/extensions/internal/E10SAddonsRollout.jsm#L24
https://github.com/MrAlex94/Waterfox/blob/5d77b0297ceb04d9c9cc9340b7a7bd0b56ca00af/browser/extensions/e10srollout/bootstrap.js#L44

**Comment by MrAlex94** [comment] 2017-12-22 14:42
A fair few people complained that e10s blocking wasn't necessary, so I [disabled](https://github.com/MrAlex94/Waterfox/commit/9c4cc5585e2d6b00ce06fcdde9d98fbd400471c6) it but seems that the problems it does cause to add-ons not compatible is greater. Will revert it I reckon for the next release.

**Comment by Atanacius** [comment] 2018-01-20 02:35
You can also do differently (as I doed just at the instant and it worked!)

Like you all, I wasn't able anymore to capture webpages (said successfully captured but not, since missed file), since release of Waterfox 56.x...

Well, fallen under your topic, and, finally tried something:

Open your Window in a NON e10s !
This is actually pretty simple to to it in Waterfox, even enabled by default, the Waterfox browser let us choose when or when not open a tab in a e10s window!

The step are: Right click on your TAB in a e10s window (that cause non enabled capture possibility) and.. just choose: "Open in a new non-e10s window".

And.. It will open this precise tab in a new non e10s window (while other window that you need in e10s remain in e10s!)

The new tab then in the new non-e10s window is able to let ScrapBook X capture pages as usual !

Thanks to Waterfox to let us choose wheter use e10s !

**Comment by iiv3** [comment] 2018-01-23 15:47
What a mess...
Waterfox 56.0.2 had the e10s menu option grayed out and this extension worked.
Waterfox 56.0.3 have the e10s active and enabled and this extension does not work.

As the author of the extension claims that it is explicitly marked as incompatible with e10s, I think we are back to square one.

**Closed as completed** 2020-06-15 20:07 UTC
