### ISSUE TITLE
(LEGAL) about:license must be changed.

### ISSUE THREAD

**Issue by Peacock365** [BrowserWorks/waterfox#497] opened 2018-03-28 09:29 UTC
about:license currently states the following at the very top:

_Binaries of this product have been made available to you by the **Mozilla Project** under the Mozilla Public License 2.0 (MPL). Know your rights._

This is problematic, as Waterfox is not an official Mozilla product. We need to change the **Mozilla Project** snippet to **Waterfox Project** (or similar) and the attached link needs to point to https://www.waterfoxproject.org/en-US/ ...

**Comment by hawkeye116477** [comment] 2018-03-28 20:30
Also on footer, „powered by Mozilla", shouldn't that be changed?

**Comment by grahamperrin** [comment] 2018-03-28 20:32
<strike>Remove, I reckon. </strike>

**Comment by MrAlex94** [comment] 2018-03-28 20:33
Yeah I’ll change about:license. Been there for years, keep forgetting about it.

In regards to Powered by mozilla, just click the link, it explains what it is.....

**Comment by grahamperrin** [comment] 2018-03-29 01:32
Oops! Strike that. I looked at the Powered by … page umpteen times, but never bothered to scroll down to the list of products!

**Comment by grahamperrin** [comment] 2018-03-29 01:38
Dupe of [Documentation: about:license · Issue #398 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/398)

**Closed as completed** 2018-05-08 21:09 UTC
