### ISSUE TITLE
Cannot Download Themes

### ISSUE THREAD

**Issue by ghost** [BrowserWorks/waterfox#1027] opened 2019-06-18 19:20 UTC
**Describe the bug**
When trying to download a them from the FireFox Theme Store, it will show an error that the Download Failed and you need to check your internet connection even though I am connected to the internet.

**To Reproduce**
1. Go to 'https://addons.mozilla.org/en-US/firefox/addon/nicothin-dark-theme/?src=hotness'
2. Click on '+ Install Theme'
3. See error by seeing the error message

**Expected behavior**
The theme should be able to download and install into Waterfox with no problems

**Screenshots**
![Screenshot (154)](https://user-images.githubusercontent.com/37266538/59713051-c3948a00-920e-11e9-8052-8f4ec9588887.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 64bit]
 - Version [56.2.10]

**Smartphone (please complete the following information):**
Only problematic on PC

**Additional context**

**Comment by laniakea64** [comment] 2019-06-18 20:20
Duplicate of https://github.com/MrAlex94/Waterfox/issues/972

**Comment by MrAlex94** [comment] 2019-06-19 12:23
Fixed in 56.2.11 https://github.com/MrAlex94/Waterfox/issues/972#issuecomment-503537849

**Closed as completed by MrAlex94** 2019-06-19 12:23 UTC
