### ISSUE TITLE
56.2.12 crashes on opening Download window / OS X 10.7.5 

### ISSUE THREAD

**Issue by MacMoinsen** [BrowserWorks/waterfox#1074] opened 2019-07-21 10:38 UTC
When I use a download link on any website, the Download window pops up and I can choose an option. But after starting the download, only parts seem to get downloaded, then everything freezes for 4 seconds and the browser crashes. After restarting and attempting to download again, the Download window may pop up but is blank, and after 2 seconds the browser crashes.

The browser also crashes after manually opening the Download window.

This bug appeared with the 56.2.12 update.

OS X 10.7.5 MacBook 2,1

Crash report:
[wf-56-2-12-crash-report.txt](https://github.com/MrAlex94/Waterfox/files/3414524/wf-56-2-12-crash-report.txt)

The crash coincides with an excessively long Console log:
[Excessive-Log-wf-56-2-12.txt](https://github.com/MrAlex94/Waterfox/files/3414546/Excessive-Log-wf-56-2-12.txt)

**Comment by grahamperrin** [comment] 2019-07-21 15:33
Probably a duplicate of [Downloads Window Open/Close causes Crash. · Issue #1059 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/1059)

**Comment by grahamperrin** [comment] 2019-09-04 01:03
https://redd.it/cz9zcy

>> … built with OS X 10.11 SDK once again, which should alleviate crashes. …

**Comment by grahamperrin** [comment] 2019-09-05 00:59
Meta/tracking: #538

**Comment by MrAlex94** [comment] 2020-08-13 20:09
Should now be resolved. https://cdn.waterfox.net/releases/osx64/installer/Waterfox%20Classic%202020.07.2%20Setup.dmg

**Closed as completed by MrAlex94** 2020-08-13 20:09 UTC
